# Generated by Django 2.2.28 on 2023-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230609_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='testtt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
