# Generated by Django 2.2.28 on 2023-06-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_testtt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abdullah_is_the_best',
            field=models.TextField(blank=True, null=True),
        ),
    ]
